### ISSUE TITLE
it will be better to provide a cli tool

### ISSUE THREAD

**Issue by zwszwszws** [saasquatch/json-schema-inferrer#10]
it will be better to provide a cli tool, thx

**Comment by slisaasquatch** [comment]
It's a valid suggestion, but I have to say it's not something I'm looking to do because it's not something that's particularly useful for myself. Also, I'd imagine it would be a relatively trivial task to build a CLI tool using this very library and something like [Commons CLI](https://commons.apache.org/proper/commons-cli/).
