### ISSUE TITLE
intelliJ gradle dependency failure

### ISSUE THREAD

**Issue by electronhead** [saasquatch/json-schema-inferrer#13]
I don't know if this question belongs here, but maybe someone has encountered this issue before.

I basically want to use this library in a production java environment using IntelliJ as the IDE.

After attempting to create a gradle dependency in the IDE, the Maven artifact for this library does not show up in the relevant artifact list.

How to reproduce:

1. press cmd-N when viewing build.gradle in the editor
2. Select Add Maven artifact dependency
3. the identifier to use is from the maven repo website: com.github.saasquatch:json-schema-inferrer:0.1.3
4. paste the identifer into the artifact search field
5. This artifact does not show up in the resulting list.

Even adding a custom repository (https://repository.mulesoft.org/nexus/content/repositories/public/) to IntelliJ from the Maven repository website does not help. This directory apparently does not to contain the desired resources.

Any thoughts or help would be greatly appreciated.

**Comment by slisaasquatch** [comment]
I think the source of the problem is likely the fact that this library is not on Maven Central. It is distributed through JitPack, at least for now. I know you can find this library [on Maven Repository here](https://mvnrepository.com/artifact/com.github.saasquatch/json-schema-inferrer), but it is on the Mulesoft repository and not Maven Central, and I am actually not the one that published it there.

So what are you trying to do here? If you are just trying to include this library as a dependency, it should be completely independent from IntelliJ, since you just need to edit the `build.gradle` file and I have successfully used this library with Gradle, Maven, and SBT.

I don't know how I'll be able to help, because currently I have no plans of publishing this library to Maven Central.

**Comment by electronhead** [comment]
Just trying to include the library as a dependency. So it looks like it's time to figure out how to do a file-based dependency in gradle. From a first reading of ...

https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:file_dependencies

...unless I'm missing something, it looks like including a project-local file dependency in build.gradle will require some convincing of folks around here.

Thanks for your help.
