### ISSUE TITLE
There is no JsonNode's key in GenericSchemaFeatureInput.

### ISSUE THREAD

**Issue by Exclamation-mark** [saasquatch/json-schema-inferrer#16]
Sometimes, I only want some keys to generate rules, but the current `GenericSchemaFeatureInputcan ` only get the type and value of the json node, not its key.
For an example:
```json
{
  "result": "success",
  "msg": "xxxxxxxxx"
}
```
I want this json gen that json schema:
```json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"result": {
			"type": "string",
                        "const": "success"
		},
		"msg": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"result",
		"msg"
	]
}
```
Now, I can't make rules to generate const only for the field `result`.

**Comment by Exclamation-mark** [comment]
If the class `GenericSchemaFeatureInput` have a api just like `getKey()`.
I can control which fields generate rules according to the key.

**Comment by slisaasquatch** [comment]
> If the class `GenericSchemaFeatureInput` have a api just like `getKey()`.

This is something I've thought about, but I eventually deemed it a can of worms that I didn't want to open. It's easy to think adding `getKey()` will solve quite a few problems problems, which it probably does. The problem is that what about array elements? What about the root element? And should `getKey()` only provide the current field name and not the full path from root? If it needs to provide the full path, which standard should it use? JSON pointer? JSON path? The list of questions can go on, but I think you get my point.

And if we back up a little, for something like this that's specific for your use case, personally I'd achieve that by post processing the schema. It's much easier to traverse the result JSON schema and make the desired modifications than jamming in a half-baked feature.

Another interface you can take a look at is `EnumExtractor`. I never implemented `const` because `const` is identical to an `enum` with one element. I'm aware that this doesn't give you exactly what you described, but you can implement a custom `EnumExtractor` similar to `EnumExtractors.validEnum` where it extracts the single possibility of `"success"`, and this will turn `"result": "success"` into an enum with one element.

```java
EnumExtractor successEnumExtractor = input -> {
	final Set<? extends JsonNode> successNodes = input.getSamples().stream()
			.filter(j -> "success".equals(j.textValue()))
			.collect(Collectors.toSet());
	return successNodes.isEmpty() ? Collections.emptySet() : Collections.singleton(successNodes);
};
```

I'll close the ticket for now, because right now I cannot come up with a solution I'm satisfied with.
