### ISSUE TITLE
how to get error positions?

### ISSUE THREAD

**Issue by operlay** [saasquatch/json-schema-inferrer#35]
Hello. how to get error positions?
 example json
{
    "totalQuantity": 1,
    "requestStatus": 1,
    "requestErorCode": 7,
    "requestErrorMessage": "",
    "attributes": [{
        "centralizedId": 01082023,
        "registryId": 1234,
        "paymentd": 1,
    }]
}
This JSON one has a bug: "centralizedId": 01082023.
Can I get information about the error?
For example: Error in line 7 character 34.

**Comment by slisaasquatch** [comment]
JSON parsing errors are not the responsibility of json-shema-inferrer, because this library does not do any JSON parsing whatsoever. It simply accepts the Jackson `JsonNode` type. What this means is that JSON parsing has to be done entirely with Jackson completely outside of this library.

I'll close the ticket for now.
