### ISSUE TITLE
State of the repo

### ISSUE THREAD

**Issue by imochurad** [saasquatch/json-schema-inferrer#7]
What is the long term plan to support and enhance this library?
I am thinking of either creating something myself or betting on this lib.
Are the artifacts published to maven repo? 
When the support of `draft-08` will be available? 
Are you open to contributors PRs?

**Comment by slisaasquatch** [comment]
* This is a library we use for our internal purposes and also my personal hobby project. Right now I don't have any major feature in mind, but I'll update this library if I have something in mind.
* The artifacts are not published to Maven Central
* 2019-09 support is something that's on my mind, but I think I'll wait for the [JSON schema validator I'm using](https://github.com/everit-org/json-schema) to support it first. Otherwise the tests won't work.
* Yes. What do you have in mind?

**Comment by slisaasquatch** [comment]
Closing the ticket for now. Feel free to reopen it if you have any questions.
